[dir]
vim           = "${HOME}"
nvim          = ""
pluginManager = "${HOME}/.vim/autoload"

[source]
vimrc         = "Rcs/.vimrc"
nvimrc        = "Rcs/init.vim"
gnvimrc       = "Rcs/ginit.vim"
pluginManager = "Rcs/plug.vim"

[target]
vimrc         = ".vimrc"
nvimrc        = "init.vim"
gnvimrc       = "ginit.vim"
pluginManager = "plug.vim"

[pluginManager]
install = true
